name: conplex
channels:
  - pytorch
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tqdm
  - black
  - black-jupyter
  - isort
  - jupyter
  - tdc
  - pytdc
  - rdkit
  - omegaconf
  - h5py
  - dgl
  - biopython
  - gensim
  - pytorch::pytorch
  - cudatoolkit=11.2
  - pytorch-lightning
  - torchmetrics
  - transformers
  - wandb
  - deepchem
  - pip:
    - fair-esm
    - dscript
    - pysmiles
    - git+https://github.com/tbepler/prose
